# Generated by Django 3.0.2 on 2020-01-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_auto_20200121_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='desconto',
            field=models.IntegerField(verbose_name='Desconto'),
        ),
    ]
